import type { AgentRunOutcome } from "../contracts/runs";
import type { AgentWorkspaceResult } from "../contracts/workspaces";
import type { AgentParameters } from "../definitions/prompt";

export function workspaceResultMetadata(result: AgentWorkspaceResult, noChanges = false): string {
    const commits = result.commits.length
        ? `${result.commits.length} commit${result.commits.length === 1 ? "" : "s"}: ${result.commits.slice(0, 8).join(", ")}${result.commits.length > 8 ? ", …" : ""}`
        : "none (worker tree matches the base revision)";
    return [
        "### Workspace result",
        `- Workspace: \`${result.workspaceId}\``,
        `- Result: \`${result.id}\``,
        `- Base revision: \`${result.baseRevision}\``,
        `- Worker revision: \`${result.workerHead}\``,
        `- Commit range: \`${result.commitRange}\``,
        `- Commits: ${commits}`,
        `- Durable ref: \`${result.durableRef ?? "none"}\``,
        noChanges
            ? "- Outcome: no changes; the parent checkout was unchanged and the workspace lease was released for reuse."
            : "- Outcome: result prepared for review; the parent checkout was unchanged.",
        noChanges
            ? "- Application: not needed."
            : "- Disposition: the parent can inspect, apply, discard, or continue this result with agent actions; the TUI remains available for manual review.",
    ].join("\n");
}

export function toolMetadataBlock(
    action: AgentParameters["action"],
    outcome: AgentRunOutcome,
    responseFollows: boolean,
): string {
    const { details } = outcome;
    const lines = [
        "<metadata>",
        responseFollows
            ? "This block contains metadata generated by the agent tool. The delegated agent's verbatim response follows after this block."
            : "This block contains metadata generated by the agent tool. This action has no delegated agent response.",
        "",
        `Action: \`${action}\``,
        `Run ID: \`${details.runId}\``,
        `Agent: \`${details.agent}\``,
        `Status: \`${details.status}\``,
        `Execution: \`${details.background ? "background" : "foreground"}\``,
    ];
    if (details.title) lines.push(`Title: ${details.title}`);
    if (!details.background) {
        lines.push("Collection: not applicable; foreground results are returned directly.");
    }
    const report = details.mutationReport;
    if (report && (
        details.mutating === true
        || report.changedFiles.length > 0
        || report.bashApproved
        || report.interrupted === true
    )) {
        const files = report.changedFiles.length
            ? report.changedFiles.map((file) => `  - \`${file}\``)
            : ["  - none tracked"];
        lines.push(
            "",
            "Mutation report:",
            `- Bash commands approved: ${report.bashApproved ? "yes" : "no"}`,
            "- Files changed by successful edit/write calls:",
            ...files,
        );
        if (report.interrupted) {
            lines.push("- The run was interrupted previously; tool mutations may be uncertain.");
        }
        if (report.bashApproved) {
            lines.push("- Approved bash commands may have changed additional files; inspect the checkout before attribution.");
        }
    }
    if (details.workspaceResult) {
        lines.push("", workspaceResultMetadata(
            details.workspaceResult,
            details.workspaceResult.workerHead === details.workspaceResult.baseRevision
                && details.workspaceResult.commits.length === 0,
        ));
    }
    if (details.error) lines.push("", `Error: ${details.error}`);
    if (outcome.additionalMetadata?.length) {
        lines.push("", ...outcome.additionalMetadata);
    }
    if (!responseFollows) lines.push("", "Tool message:", outcome.content);
    lines.push("</metadata>");
    return lines.join("\n");
}

export function formatAgentToolContent(
    action: AgentParameters["action"],
    outcome: AgentRunOutcome,
): string {
    const hasResponse = outcome.hasResponse === true;
    const metadata = toolMetadataBlock(action, outcome, hasResponse);
    return hasResponse ? `${metadata}\n\n${outcome.content}` : metadata;
}
